<h1>Задание 1</h1>

На маркетплейсе есть огромный объем данных содержащий записи о продажах различных продуктов. Наша цель — рассчитать общий доход, полученный от каждого продукта за определённый период. 

Необходимо решить задачу через классический python, numpy и numpy с использованием векторизации


Данные: 
products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'] (при решении через numpy необходимо представить это в виде np.array() )
prices = [20000, 3000, 45600, 5000] (при решении через numpy необходимо представить это в виде np.array() ) 

Данные о продажах необходимо сгенерировать самостоятельно и вывести в одном параграфов в ноутбуке, ниже приведен пример генерации случайных значений 

In [1]:
#через python

import time

import random
variant = 16 
sales = [ [random.randint(0, variant+100) for i in range(100000)], [random.randint(0, variant+100) for i in range(100000)], [random.randint(0, variant+100) for i in range(100000)], [random.randint(0, variant+100) for i in range(100000)]]

products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны']
prices = [20000, 3000, 45600, 5000]

i=0
income=[]
start_time = time.time()
for i in range(4):
    income.append(prices[i]*sum(sales[i]))
print(income)
end_time = time.time()
python_time = end_time - start_time
print(python_time)

[115687440000, 17413290000, 264036494400, 28971840000]
0.0030143260955810547


In [2]:
#через numpy

import numpy as np
products1 = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices1 = np.array([20000, 3000, 45600, 5000])
sales1 = np.zeros((4,100000), np.int64)
income1 = np.zeros((4,3))
#print(income1)

#присваиваю рандомные значения из предыдущей реализации, чтобы они совпадали
for i in range(4):
    for j in range(100000):
        sales1[i][j] = sales[i][j]
print(sales1)

i=0
income1=np.zeros(4, np.int64)
print(income1)
start_time = time.time()
for i in range(4):
    income1[i] = prices1[i]*sum(sales1[i])
print(income1)
end_time = time.time()
numpy_time = end_time - start_time
print(numpy_time)

[[110  43   7 ...  29  46  78]
 [ 22   2  11 ...  75  21  14]
 [105 104 109 ...   6 100  53]
 [ 21  66  46 ...   3  99  88]]
[0 0 0 0]
[115687440000  17413290000 264036494400  28971840000]
0.0269625186920166


In [3]:
#через numpy с векторизацией
sales2 = np.array([sum(sales1[0]), sum(sales1[1]), sum(sales1[2]), sum(sales1[3])])
#print(sales2)
start_time = time.time()
income2 = np.zeros((4,1))
income2 = prices1*sales2
print(income2)
end_time = time.time()
numpy_vec_time = end_time - start_time
print(numpy_vec_time)

[115687440000  17413290000 264036494400  28971840000]
0.0008680820465087891


In [67]:
#вывод доходов, полученных разными способами
print('Доход от товара автомобиль HAVAL:', income[0], income1[0], income2[0], sep=', ')
print('Доход от товара обувь:', income[1], income1[1], income2[1], sep=', ')
print('Доход от товара одежда:', income[2], income1[2], income2[2], sep=', ')
print('Доход от товара телефоны:', income[3], income1[3], income2[3], sep=', ')
print('\n')
#сравнение времени
print('Время через python:', python_time)
print('Время через numpy:', numpy_time)
print('Время через numpy с векторизацией:', numpy_vec_time)

Доход от товара автомобиль HAVAL:, 115687440000, 115687440000, 115687440000
Доход от товара обувь:, 17413290000, 17413290000, 17413290000
Доход от товара одежда:, 264036494400, 264036494400, 264036494400
Доход от товара телефоны:, 28971840000, 28971840000, 28971840000


Время через python: 0.0030143260955810547
Время через numpy: 0.0269625186920166
Время через numpy с векторизацией: 0.0008680820465087891


Данные в различных реализациях должны совпадать.

После генерации необходимо сравнить доход от каждого продукта и время на выполнение. 

<h1>Задание 2</h1>

Необходимо написать с использованием numpy реализацию одного из следующих алгоритмов: 

- heapsort (вариант: 1,5,9,13,17,21)

- mergesort (вариант: 2,6,10,14,18,22)

- stable (вариант: 3,7,11,15,19)

- quicksort (вариант: 4,8,12,16,20) 

Сравнить скорость выполнения этих алгоритмов на чистом python, вашей реализации и numpy.sort() 

In [8]:
#quicksort с использованием numpy
def quicksort(x):
    if x.size == 1 or x.size == 0:
        return x
    else:
        pivot = x[0]
        i = 0
        for j in range(x.size-1):
            if x[j+1] < pivot:
                x[j+1],x[i+1] = x[i+1], x[j+1]
                i += 1
        x[0],x[i] = x[i],x[0]
        first_part = quicksort(x[:i])
        second_part = quicksort(x[i+1:])
        #print(first_part)
        #print(second_part)
        first_part = np.append(first_part, x[i])
        return (np.concatenate([first_part, second_part]))

g=np.array([84,32,94,72,93,62,94])
print(quicksort(g))

a = np.array([random.randint(0, 1000) for i in range(1000)])


[32 62 72 84 93 94 94]


In [9]:
#время qiucksort с использованием numpy
%%timeit
quicksort(a)


77 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
#время np.sort
%%timeit
np.sort(a)


7.12 µs ± 416 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<h1>Задание 3</h1> 

У нас есть данные о потреблении алкоголя о потреблнеии Алкоголя в мире https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption. 

Давайте представим эти данные в виде структурированных массивов и определим, где же люди пьют больше вина, пива и других спиртных напитков.

In [21]:
data = np.genfromtxt('drinks.csv', delimiter=',', skip_header=1, dtype={
        "names": ["country", "beer_servings", "spirit_servings", "wine_servings", "total_litres_of_pure_alcohol"],
        "formats": ["U16", "i4","i4","i4","f8"]
    })


print(data.dtype)

[('country', '<U16'), ('beer_servings', '<i4'), ('spirit_servings', '<i4'), ('wine_servings', '<i4'), ('total_litres_of_pure_alcohol', '<f8')]


In [22]:
for _ in data:
    print(_)

('Afghanistan', 0, 0, 0, 0.)
('Albania', 89, 132, 54, 4.9)
('Algeria', 25, 0, 14, 0.7)
('Andorra', 245, 138, 312, 12.4)
('Angola', 217, 57, 45, 5.9)
('Antigua & Barbud', 102, 128, 45, 4.9)
('Argentina', 193, 25, 221, 8.3)
('Armenia', 21, 179, 11, 3.8)
('Australia', 261, 72, 212, 10.4)
('Austria', 279, 75, 191, 9.7)
('Azerbaijan', 21, 46, 5, 1.3)
('Bahamas', 122, 176, 51, 6.3)
('Bahrain', 42, 63, 7, 2.)
('Bangladesh', 0, 0, 0, 0.)
('Barbados', 143, 173, 36, 6.3)
('Belarus', 142, 373, 42, 14.4)
('Belgium', 295, 84, 212, 10.5)
('Belize', 263, 114, 8, 6.8)
('Benin', 34, 4, 13, 1.1)
('Bhutan', 23, 0, 0, 0.4)
('Bolivia', 167, 41, 8, 3.8)
('Bosnia-Herzegovi', 76, 173, 8, 4.6)
('Botswana', 173, 35, 35, 5.4)
('Brazil', 245, 145, 16, 7.2)
('Brunei', 31, 2, 1, 0.6)
('Bulgaria', 231, 252, 94, 10.3)
('Burkina Faso', 25, 7, 7, 4.3)
('Burundi', 88, 0, 0, 6.3)
("Cote d'Ivoire", 37, 1, 7, 4.)
('Cabo Verde', 144, 56, 16, 4.)
('Cambodia', 57, 65, 1, 2.2)
('Cameroon', 147, 1, 4, 5.8)
('Canada', 240, 122, 

In [23]:
print(max(data["beer_servings"]))
print(data[data["beer_servings"] == max(data["beer_servings"])]["country"])

376
['Namibia']


In [24]:
print(max(data["spirit_servings"]))
print(data[data["spirit_servings"] == max(data["spirit_servings"])]["country"])

438
['Grenada']


In [25]:
print(max(data["wine_servings"]))
print(data[data["wine_servings"] == max(data["wine_servings"])]["country"])

370
['France']


In [26]:
print(max(data["total_litres_of_pure_alcohol"]))
print(data[data["total_litres_of_pure_alcohol"] == max(data["total_litres_of_pure_alcohol"])]["country"])

14.4
['Belarus']


<h1>Задание 4</h1> 

У нас есть Полный каталог всех случаев, когда кто-то проклинал или истекал кровью в фильме Квентина Тарантино. https://github.com/fivethirtyeight/data/tree/master/tarantino

Давайте представим эти данные в виде структурированных массивов и определим:

- число проклятий, летальных исходов и их отношение по фильмам 

- частота употребления конкретных прокрятий 

- распределение времени между проклятиями 

In [27]:
data = np.genfromtxt('tarantino.csv', delimiter=',', skip_header=1, dtype={
        "names": ["movie", "type", "word", "minutes_in"],
        "formats": ["U16", "U16","U16","f8"]
    })


print(data.dtype)

[('movie', '<U16'), ('type', '<U16'), ('word', '<U16'), ('minutes_in', '<f8')]


In [28]:
for _ in data:
    print(_)

('Reservoir Dogs', 'word', 'dick', 0.4)
('Reservoir Dogs', 'word', 'dicks', 0.43)
('Reservoir Dogs', 'word', 'fucked', 0.55)
('Reservoir Dogs', 'word', 'fucking', 0.61)
('Reservoir Dogs', 'word', 'bullshit', 0.61)
('Reservoir Dogs', 'word', 'fuck', 0.66)
('Reservoir Dogs', 'word', 'shit', 0.9)
('Reservoir Dogs', 'word', 'fuck', 1.43)
('Reservoir Dogs', 'word', 'dicks', 1.56)
('Reservoir Dogs', 'word', 'fuck', 1.66)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dick', 1.75)
('Reservoir Dogs', 'word', 'dicks', 1.75)
('Reservoir Dogs', 'word', 'motherfucker', 1.83)
('Reservoir Dogs', 'word', 'dick', 1.96)
('Reservoir Dogs', 'word', 'pussy', 2.15)
('Reservoir Dogs', 'word', 'fucks', 2.18)
('Reservoir Dogs', 'word', 'fuck', 2.3)
('Reservoir Dogs', 'word', 'fucking', 

('Pulp Fiction', 'word', 'fucked', 112.87)
('Pulp Fiction', 'word', 'fucked', 112.87)
('Pulp Fiction', 'word', 'fuck', 112.88)
('Pulp Fiction', 'word', 'goddamn', 112.95)
('Pulp Fiction', 'word', 'damn', 112.97)
('Pulp Fiction', 'word', 'fuck', 112.98)
('Pulp Fiction', 'word', 'shit', 113.08)
('Pulp Fiction', 'word', 'motherfuckers', 113.13)
('Pulp Fiction', 'death', '', 113.37)
('Pulp Fiction', 'word', 'fuck', 113.65)
('Pulp Fiction', 'word', 'goddamn', 113.75)
('Pulp Fiction', 'word', 'fucking', 113.93)
('Pulp Fiction', 'word', 'shit', 114.03)
('Pulp Fiction', 'word', 'motherfucking', 114.43)
('Pulp Fiction', 'word', 'fucking', 114.52)
('Pulp Fiction', 'word', 'shit', 114.53)
('Pulp Fiction', 'word', 'fucking', 114.57)
('Pulp Fiction', 'word', 'shit', 114.6)
('Pulp Fiction', 'word', 'shit', 114.63)
('Pulp Fiction', 'word', 'fucking', 114.75)
('Pulp Fiction', 'word', 'fucking', 114.85)
('Pulp Fiction', 'word', 'n-word ', 115.08)
('Pulp Fiction', 'word', 'shit', 115.12)
('Pulp Fiction'

('Jackie Brown', 'word', 'n-word ', 16.23)
('Jackie Brown', 'word', 'goddamn', 16.25)
('Jackie Brown', 'word', 'shit', 16.28)
('Jackie Brown', 'word', 'ass', 16.3)
('Jackie Brown', 'word', 'ass', 16.33)
('Jackie Brown', 'word', 'motherfucking', 16.35)
('Jackie Brown', 'word', 'n-word ', 16.38)
('Jackie Brown', 'word', 'motherfucker', 16.47)
('Jackie Brown', 'word', 'hell', 16.52)
('Jackie Brown', 'word', 'shit', 16.55)
('Jackie Brown', 'word', 'ass', 16.58)
('Jackie Brown', 'word', 'shit', 16.65)
('Jackie Brown', 'word', 'n-word ', 16.77)
('Jackie Brown', 'word', 'fucking', 16.87)
('Jackie Brown', 'word', 'n-word ', 17.12)
('Jackie Brown', 'word', 'ass', 17.22)
('Jackie Brown', 'word', 'n-word ', 17.25)
('Jackie Brown', 'word', 'fuck', 17.3)
('Jackie Brown', 'word', 'shit', 17.4)
('Jackie Brown', 'word', 'fucking', 17.42)
('Jackie Brown', 'word', 'ass', 17.48)
('Jackie Brown', 'word', 'fucking', 17.52)
('Jackie Brown', 'word', 'n-word ', 17.82)
('Jackie Brown', 'word', 'n-word ', 17.82

In [34]:
#число проклятий
words = data[data["type"] == 'word']["type"]
deaths = data[data["type"] == 'death']["type"]
print('число проклятий:', words.size)
print('число смертей:', deaths.size)

число проклятий: 1704
число смертей: 190


In [59]:
type_Reservoir_Dogs = data[data["movie"] == 'Reservoir Dogs']["type"]
i = 0
words_Reservoir_Dogs = 0
deaths_Reservoir_Dogs = 0
for i in range (type_Reservoir_Dogs.size):
    if type_Reservoir_Dogs[i] == 'word':
        words_Reservoir_Dogs+=1
    else:
        deaths_Reservoir_Dogs+=1
        
type_Pulp_Fiction = data[data["movie"] == 'Pulp Fiction']["type"]
i = 0
words_Pulp_Fiction = 0
deaths_Pulp_Fiction = 0
for i in range (type_Pulp_Fiction.size):
    if type_Pulp_Fiction[i] == 'word':
        words_Pulp_Fiction+=1
    else:
        deaths_Pulp_Fiction+=1       
        
type_Bill1 = data[data["movie"] == 'Kill Bill: Vol. ']["type"]
i = 0
words_Bill1 = 0
deaths_Bill1 = 0
for i in range (type_Bill1.size):
    if type_Bill1[i] == 'word':
        words_Bill1+=1
    else:
        deaths_Bill1+=1    

type_Basterds = data[data["movie"] == 'Inglorious Baste']["type"]
i = 0
words_Basterds = 0
deaths_Basterds = 0
for i in range (type_Basterds.size):
    if type_Basterds[i] == 'word':
        words_Basterds+=1
    else:
        deaths_Basterds+=1    
        
type_Django = data[data["movie"] == 'Django Unchained']["type"]
i = 0
words_Django = 0
deaths_Django = 0
for i in range (type_Django.size):
    if type_Django[i] == 'word':
        words_Django+=1
    else:
        deaths_Django+=1   
        
type_Brown = data[data["movie"] == 'Jackie Brown']["type"]
i = 0
words_Brown = 0
deaths_Brown = 0
for i in range (type_Brown.size):
    if type_Brown[i] == 'word':
        words_Brown+=1
    else:
        deaths_Brown+=1   
        
print("отношение количества проклятий к количеству смертей в фильме Reservoir_Dogs:", words_Reservoir_Dogs/deaths_Reservoir_Dogs)        
print("отношение количества проклятий к количеству смертей в фильме Pulp Fiction:", words_Pulp_Fiction/deaths_Pulp_Fiction)
print("отношение количества проклятий к количеству смертей в фильме Kill Bill: Vol. 1:", words_Bill1/deaths_Bill1)
print("отношение количества проклятий к количеству смертей в фильме Inglorious Basterds", words_Basterds/deaths_Basterds)
print("отношение количества проклятий к количеству смертей в фильме Django Unchained:", words_Django/deaths_Django)
print("отношение количества проклятий к количеству смертей в фильме Jackie Brown:", words_Basterds/deaths_Basterds)

отношение количества проклятий к количеству смертей в фильме Reservoir_Dogs: 42.1
отношение количества проклятий к количеству смертей в фильме Pulp Fiction: 67.0
отношение количества проклятий к количеству смертей в фильме Kill Bill: Vol. 1: 1.7027027027027026
отношение количества проклятий к количеству смертей в фильме Inglorious Basterds 1.2083333333333333
отношение количества проклятий к количеству смертей в фильме Django Unchained: 5.574468085106383
отношение количества проклятий к количеству смертей в фильме Jackie Brown: 1.2083333333333333


In [63]:
uwords = np.unique(data["word"])
print(uwords)
print(uwords.size)

['' 'ass' 'asses' 'asshead' 'asshole' 'assholes' 'bastard' 'bastards'
 'bitch' 'bitches' 'bullshit' 'chickenshit' 'cockblockery' 'cocksucker'
 'cunt' 'cunts' 'damn' 'damned' 'dick' 'dickless' 'dicks' 'dumbass'
 'faggot' 'fuck' 'fucked' 'fucker' 'fuckers' 'fuckface' 'fuckhead'
 'fucking' 'fucks' 'fuckup' 'goddamn' 'goddamned' 'gook' 'gooks' 'hell'
 'horeshit' 'horseshit' 'jackass' 'jap' 'japs' 'jew (verb)' 'merde'
 'motherfucker' 'motherfuckers' 'motherfucking' 'n-word ' 'negro ' 'pussy'
 'shit' 'shithead' 'shitless' 'shitload' 'shittiest' 'shitting' 'shitty'
 'slope' 'slut' 'squaw' 'wetback']
61


In [66]:
#различных много, какие надо было посчитать?
fwords = data[data["word"] == 'fuck']["word"]
awords = data[data["word"] == 'ass']["word"]
gwords = data[data["word"] == 'goddamn']["word"]
print('число проклятия fuck:', fwords.size)
print('число проклятия ass:', awords.size)
print('число проклятия goddamn:', gwords.size)

число проклятия fuck: 213
число проклятия ass: 140
число проклятия goddamn: 113
