### Сделайте транспонирование матрицы без использования numpy и других библиотек

In [1]:
def transpose(matrix):
    transposed = matrix
    for i in range(0, len(transposed)):
        for j in range(0, len(transposed[i])):
            if(i<j):
                transposed[i][j], transposed[j][i] = transposed[j][i], transposed[i][j]
    return transposed

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(transpose(matrix))

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [2]:
import numpy as np

### Теперь сделайте транспонирование с помощью numpy

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [4]:
t_matrix = matrix.transpose()
print(t_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Сделайте умножение транспонированного input_vector на weights_matrix

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

input_vector = np.array([[0.5], 
                         [0.8]])

weights_matrix = np.array([[0.2, 0.3], 
                           [0.6, -0.1]])


hidden_layer_output = sigmoid(np.dot(input_vector.transpose(),weights_matrix))

print(hidden_layer_output)

[[0.64106741 0.51749286]]



### Используя матричные операции, найдите веса линейной регрессии.

Пусть у вас есть следующие данные:

- $ X $ - матрица признаков размерности $ m \times n $, где $ m $ - количество объектов, а $ n $ - количество признаков.
- $ y $ - вектор ответов размерности $ m \times n $

Веса линейной регрессии $ w $ можно найти по формуле:

$  w = (X^T X)^{-1} X^T y  $ (-1 - это обратная матрица)

Напишите функцию, для нахождения $w$


In [8]:
import numpy as np

def compute_weights(X, y):
    xtx = X.T @ X

    if np.linalg.det(xtx) == 0:
        raise ValueError("Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.")
    w = ((np.linalg.inv(xtx)).dot(X.T)).dot(y)
    return w



In [11]:
X = np.array([
    [1, 2, 3, 6, 5, 6],
    [2, 4, 2, 4, 6, 7],
    [3, 6, 4, 8, 7, 8],
    [4, 8, 3, 6, 8, 9],
    [5, 10, 5, 10, 9, 10],
    [6, 12, 1, 2, 10, 11]
])

y = np.random.rand(6, 1)
weights = compute_weights(X, y)


ValueError: Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.

In [14]:
X = np.array([
    [1, 2],
    [2, 3]
])

y = np.random.rand(2, 1)
weights = compute_weights(X, y)
print(weights)

[[-2.04207774]
 [ 1.47834022]]


### В том случае, если у матрицы есть линейно зависимые столбцы посчитать веса не получится

In [54]:
X1 = np.array([
    [1, 2, 3, 4, 5, 6],
    [2, 4, 2, 8, 6, 7],
    [3, 6, 4, 12, 7, 8],
    [4, 8, 3, 16, 8, 9],
    [5, 10, 5, 20, 9, 10],
    [6, 12, 1, 24, 10, 11]
])


y1 = np.random.rand(6, 1)
weights = compute_weights(X1, y1)

ValueError: Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.

### Придумайте способ, который может у любой матрицы X найти линейно зависимые столбцы и напишите такую функцию. После этого примените эту функцию к матрице X1 

In [56]:

def find_dep(X):
    cur=[]
    dep=[]
    n=1
    for i in range(len(X)):
        cur.append(X[i,:])
        if np.linalg.matrix_rank(cur)==n:
            n+=1
        else:
            dep.append(X[i,:])
    return dep

#сейчас выведем линейно зависимые столбцы из матрицы Х1
print(find_dep(X1))

[array([ 4,  8,  3, 16,  8,  9]), array([ 5, 10,  5, 20,  9, 10]), array([ 6, 12,  1, 24, 10, 11])]


### Давайте рассмотрим матричное уравнение вида:

### $ AX = B $

### Напишите код, который найдет $X$


In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
X = (np.linalg.inv(A)).dot(B)
print("Матрица X:")
print(X)

Матрица X:
[[-3. -4.]
 [ 4.  5.]]


### Напишите код, который находит собственные значения и векторы матрицы A

In [28]:
import numpy as np

A = np.array([[4, -2],
              [1,  3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Собственные значения:")
print(eigenvalues)
print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[3.5+1.32287566j 3.5-1.32287566j]

Собственные векторы:
[[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415-0.54006172j 0.20412415+0.54006172j]]


### Почему числа получились какие-то странные?

In [41]:
# почему странные? они просто комплексные получились